### ISSUE TITLE
路由生成代码当中 queries 改为逐层继承

### ISSUE THREAD

**Issue by chenyong** [jimengio/router-code-generator#18]
现在的 generator 当中没有处理. 比如

```json
[
  {
    "path": "a",
    "queries": ["x"],
    "next": [
      { "path": "b" }
    ]
  }
]
```

在 http://fe.jimu.io/router-code-generator/ 当中生成的代码, `/a` 是包含代码 query 数据的,

```js
path: ( queries?: IGenQueryA) => `/a?${qsStringify(queries)}`,
go: ( queries?: IGenQueryA) => switchPath(`/a?${qsStringify(queries)}`),
```

`/a/b` 路由当中没有继承 `queries`,

```js
path: () => `/a/b`,
go: () => switchPath(`/a/b`),
```

需要改一下支持 queries 的继承. 目前 https://github.com/jimengio/router-code-generator/pull/17 当中的 `query` 类型是有基础的.

**Comment by jiyinyiyong** [comment]
https://github.com/jimengio/router-code-generator/pull/23
